---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:
    - name: WORKSPACE_ID
      description: workspace id
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the IBM Cloud API key
    - name: acc-region
      description: Account region
    - name: enable-automatic-plan-apply
      description: if true, a plan and apply will be automatically executed upon changes to the template code
    - name: template-file
      description: template file url
    - name: sql-query-service-name
      description: sql query service name
    - name: sql-query-service-plan
      description: sql query service plan
    - name: sql-query-region
      description: sql query region
    - name: template-file-github-token
      description: github token
  workspaces:
    - name: artifacts
  tasks:
    - name: workspace
      taskRef:
        name: create-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: template-file
          value: $(params.template-file) 
        - name: template-file-github-token
          value: (params.template-file-github-token)
    - name: plan
      runAfter: [workspace]
      taskRef:
        name: plan-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
        - name: template-file
          value: $(params.template-file) 
        - name: template-file-github-token
          value: (params.template-file-github-token)
    - name: apply
      runAfter: [plan]
      taskRef:
        name: apply-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
        - name: template-file
          value: $(params.template-file) 
        - name: template-file-github-token
          value: (params.template-file-github-token)
    - name: sql-instance
      runAfter: [apply]
      taskRef:
        name: sql-instance
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: sql-query-service-name
          value: $(params.sql-query-service-name)
        - name: sql-query-service-plan
          value: $(params.sql-query-service-plan)
        - name: sql-query-region
          value: $(params.sql-query-region)
