---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:
    - name: WORKSPACE_ID
      description: workspace id
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the IBM Cloud API key
    - name: acc-region
      description: Account region
    - name: workspace-name
      description: Workspace name
    - name: enable-automatic-plan-apply
      description: if true, a plan and apply will be automatically executed upon changes to the template code
  workspaces:
    - name: artifacts
  tasks:
    - name: workspace
      taskRef:
        name: create-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: workspace-name
          value: $(params.workspace-name)
    - name: plan
      runAfter: [workspace]
      taskRef:
        name: plan-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: workspace-name
          value: $(params.workspace-name)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
    - name: apply
      runAfter: [plan]
      taskRef:
        name: apply-task
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: workspace-name
          value: $(params.workspace-name)
        - name: enable-automatic-plan-apply
          value: $(params.enable-automatic-plan-apply)
    - name: sql-instance
      runAfter: [apply]
      taskRef:
        name: sql-instance
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: apikey
          value: $(params.apikey)
        - name: acc-region
          value: $(params.acc-region)
        - name: workspace-name
          value: $(params.workspace-name)
