apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-task
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the ibmcloud api key
    - name: acc-region
      description: Account region
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: create-workspace
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2
      env:
        - name: IBM_CLOUD_API
          value: $(params.ibmcloud-api)
      command: ["/bin/bash", "-c"]
      args:
        - |
          echo "Creating schematic workspace..................."

          # force login (required by schematics cli)
          ibmcloud login --apikey $(params.apikey) -a "$(params.ibmcloud-api)" -r $(params.acc-region)

          # Output in json format
          #ibmcloud schematics version --output json

          # To find the ID of your workspace
          # ibmcloud schematics workspace list

          # Get details of a workspace
          # ibmcloud schematics workspace action --id <workspace-id>
          # https://github.com/rajeev159/terraform-provider-ibm/blob/master/examples/workspace.json
          
          curl -LJO https://raw.githubusercontent.com/rajeev159/terraform-provider-ibm/master/examples/workspace.json
          ibmcloud schematics workspace new --file workspace.json --json


