apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-task
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the ibmcloud api key
    - name: acc-region
      description: Account region
    - name: template-file
      description: template file url
    - name: template-file-github-token
      description: github token
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: create-workspace
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2
      env:
        - name: IBM_CLOUD_API
          value: $(params.ibmcloud-api)
        - name: TEMPLATE_FILE_GITHUB_TOKEN
          value: $(params.template-file-github-token)
        - name: TEMPLATE_FILE
          value: $(params.template-file)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -x
          echo "Login to ibm cloud..................."
          ERR_NUM=0
          # force login (required by schematics cli)
          ibmcloud login --apikey $(params.apikey) -a "$(params.ibmcloud-api)" -r $(params.acc-region)
          # To find the ID of your workspace
          echo "file path1"
          echo "https://$TEMPLATE_FILE@$TEMPLATE_FILE"
          echo "https://$TEMPLATE_FILE_GITHUB_TOKEN@$TEMPLATE_FILE"
          WORKSPACE_LIST=$(ibmcloud schematics workspace list --json) 
          WORKSPACE_LIST_JSON=$(echo $WORKSPACE_LIST | jq ".workspaces")
          echo "https://${TEMPLATE_FILE_GITHUB_TOKEN}@$TEMPLATE_FILE"
          curl -LJO https://$(params.template-file-github-token)@$TEMPLATE_FILE
          WORKSPACE_NAME=$(cat workspace.json | jq ".name" | sed 's/"//g')

          for row in $(echo "${WORKSPACE_LIST_JSON}" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            if [[ $WORKSPACE_NAME -eq $(_jq '.name') ]]; then
              echo "Workspace name already exists: $WORKSPACE_NAME"
              exit 1
            fi
          done
          sleep 10
          
          echo "Creating workspace....................."
          ((ERR_NUM=ERR_NUM+$?))
          WORKSPACE=$(ibmcloud schematics workspace new --file workspace.json --json) 
          ((ERR_NUM=ERR_NUM+$?))
          WORKSPACE_ID=$(echo $WORKSPACE | jq ".id" | sed 's/"//g')
          echo "WORKSPACE ID:  $WORKSPACE_ID"
          if [ $ERR_NUM -ne 0 ]; then
            echo "Error in creating workspace........................"
            exit $ERR_NUM
          else
            echo "Workspace created with id: $WORKSPACE_ID"
          fi
          sleep 30
          


