apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sql-instance
spec:
  params:
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: apikey
      description: the ibmcloud api key
    - name: acc-region
      description: Account region
    - name: sql-query-service-name
      description: sql query service name
    - name: sql-query-service-plan
      description: sql query service plan
    - name: sql-query-region
      description: sql query region
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: create-sql-instance
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2
      env:
        - name: IBM_CLOUD_API
          value: $(params.ibmcloud-api)
        - name: SQL_QUERY_SERVICE_NAME
          value: $(params.sql-query-service-name)
        - name: SQL_QUERY_SERVICE_PLAN
          value: $(params.sql-query-service-plan)
        - name: SQL_QUERY_REGION
          value: $(params.sql-query-region)
      command: ["/bin/bash", "-c"]
      args:
        - |
          #set -x
          # force login (required by schematics cli)
          ibmcloud login --apikey $(params.apikey) -a "$(params.ibmcloud-api)" -r $(params.acc-region)
          echo "Create SQL instance..................."
          if ibmcloud resource service-instance $SQL_QUERY_SERVICE_NAME > /dev/null 2>&1; then
            echo "LogDNA service $SQL_QUERY_SERVICE_NAME already exists"
            exit 1
          else
            echo "Creating SQL Query Service..."
            ibmcloud target -g Default
            ibmcloud resource service-instance-create $SQL_QUERY_SERVICE_NAME sql-query "$SQL_QUERY_SERVICE_PLAN" $SQL_QUERY_REGION
          fi
          